/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>

#line 1 "tests.check"
#include <check.h>

#include "Smart_calc.h"

#define EPS 1e-7
#define EPS2 1e-2
/*
double string_calc(char *string, double x_number) {
    Nn *A = NULL;
    polish_notation(string, &A, x_number);
    double result = calculate(&A);
    return result;
}
*/
START_TEST(test_0) {
#line 15
  char *string = "1.123+212.1";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 213.223, EPS);
}
END_TEST

START_TEST(test_1) {
#line 23
  char *string = "-(2+(1+1)+3)+55mod8+1.123+2.121-5*(1+1)+8";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 1.244, EPS);
}
END_TEST

START_TEST(test_2) {
#line 29
  char *string = "11mod3";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 2, EPS);
}
END_TEST

START_TEST(test_3) {
#line 35
  char *string = "5.0/6.0*7.0";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 5.8333333, EPS);
}
END_TEST

START_TEST(test_4) {
#line 42
  char *string = "2+3+(3*4)+(5.1+6.7)";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 28.8, EPS);
}
END_TEST

START_TEST(test_5) {
#line 49
  char *string = "11.0+12.0*13.0";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 167, EPS);
}
END_TEST

START_TEST(test_6) {
#line 56
  char *string = "55mod8";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 7, EPS);
}
END_TEST

START_TEST(test_7) {
#line 63
  char *string = "1.0/2.0*(2.0-1.0)";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 0.5, EPS);
}
END_TEST

START_TEST(test_8) {
#line 70
  char *string = "2^2^2";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 16, EPS);
}
END_TEST

START_TEST(test_9) {
#line 76
  char *string = "2^3^2";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 512, EPS);
}
END_TEST

START_TEST(test_10) {
#line 82
  char *string = "(cos(1/3)*sin(1.352^9/(4+3))/76.56)*log(150)";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 0.0223863, EPS);
}
END_TEST

START_TEST(test_11) {
#line 88
  char *string = "cos(1/3)*sin(1.352^9/(4+3))";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 0.7876032, EPS);
}
END_TEST

START_TEST(test_12) {
#line 94
  char *string = "cos(431.2*2.0^2.0/8.0)";  //  cos((431.2*2.0)^2.0/8.0)
                                            //  priority * higher than ^
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, -0.3902501, EPS);  // 2.7950166
}
END_TEST

START_TEST(test_13) {
#line 100
  char *string = "2+9.3-8^3/(4+56.2)";  //    2+9.3-8^3/(4+56.2)"
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 2.7950166, EPS);  //
  //
}
END_TEST

START_TEST(test_14) {
#line 107
  char *string = "2*x";  //
  double result = 0;
  double x_number = 3;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 6, EPS);  //
}
END_TEST

START_TEST(test_15) {
#line 114
  char *string = "1+2*x";
  double result = 0;
  double x_number = 3;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 7, EPS);
}
END_TEST

START_TEST(test_16) {
#line 120
  char *string = "1+sqrt(4)-1/2*sin(3^2-2)";
  double result = 0;
  double x_number = 3;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 2.6715067, EPS);
}
END_TEST

START_TEST(test_17) {
#line 126
  char *string = "2+sin(+3)";
  double result = 0;
  double x_number = 3;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 2.1411200, EPS);
}
END_TEST

START_TEST(test_18) {
#line 132
  char *string = "5+4*2/(1-5)";
  double result = 0;
  double x_number = 3;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 3, EPS);
}
END_TEST

START_TEST(test_19) {
#line 138
  char *string = "4+asin1";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 5.5707963, EPS);
}
END_TEST

START_TEST(test_20) {
#line 145
  char *string = "3+2+2*3";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 11, EPS);
}
END_TEST

START_TEST(test_21) {
#line 152
  char *string = "3.0/(3.0+3.0)*4.0";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 2, EPS);
}
END_TEST

START_TEST(test_22) {
#line 159
  char *string = "3*4+2+9+(6.1+7.2)";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 36.3, EPS);
}
END_TEST

START_TEST(test_22_a) {
#line 166
  char *string = "3.0/2.0*(3.0-1.0)";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 3, EPS);
}
END_TEST

START_TEST(test_23) {
#line 173
  char *string = "(0-1-2-(0-3)-4)-5-(0-6)";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, -3, EPS);
}
END_TEST

START_TEST(test_24) {
#line 180
  char *string = "(0-1-2-(0-3)-4)-5-(0-6)";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, -3, EPS);
}
END_TEST

START_TEST(test_25) {
#line 186
  char *string = "log9000";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, log10(9000), EPS);
}
END_TEST

START_TEST(test_26) {
#line 192
  char *string = "ln9000";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, log(9000), EPS);
}
END_TEST

START_TEST(test_27) {
#line 199
  char *string = "ln9000";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, log(9000), EPS);
}
END_TEST

START_TEST(test_28) {
#line 205
  char *string = "sqrt(4)-1/2*sin(3^2-2)";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 1.6715067, EPS);
}
END_TEST

START_TEST(test_29) {
#line 212
  char *string = "sin(+4)";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, sin(+4), EPS);
}
END_TEST

START_TEST(test_30) {
#line 219
  char *string = "sin(+4)";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, sin(+4), EPS);
}
END_TEST

START_TEST(test_31) {
#line 226
  char *string = "-9.0mod(-4.0)";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, -9 % -4, EPS);
}
END_TEST

START_TEST(test_32) {
#line 233
  char *string = "4+4*2/(1-5)";
  double result1 = 0;
  double result2 = 4 + 4 * 2 / (1 - 5);
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_33) {
#line 241
  char *string = "1.5*4+4*2/1-5";
  double result1 = 0;
  double result2 = 1.5 * 4 + 4 * 2 / 1 - 5;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_34) {
#line 249
  char *string = "6+4*(2.0/1.0-5)";
  double result1 = 0;
  double result2 = 6 + 4 * (2.0 / 1.0 - 5);
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_35) {
#line 256
  char *string = "4.5/2.3+(4*2/1-5)";
  double result1 = 0;
  double result2 = 4.5 / 2.3 + (4 * 2 / 1 - 5);
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_36) {
#line 263
  char *string = "4+4*(2/1)-5";
  double result1 = 0;
  double result2 = 4 + 4 * (2 / 1) - 5;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_37) {
#line 270
  char *string = "4.25+(4*2/1)-5";
  double result1 = 0;
  double result2 = 4.25 + (4 * 2 / 1) - 5;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_38) {
#line 277
  char *string = "3+(-(-(-(-1))))";
  double result1 = 0;
  double result2 = 3 + (-(-(-(-1))));
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_39) {
#line 284
  char *string = "(3+3*2/1)-6";
  double result1 = 0;
  double result2 = (3 + 3 * 2 / 1) - 6;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_40) {
#line 292
  char *string = "4+(4*2)/1-5";
  double result1 = 0;
  double result2 = 4 + (4 * 2) / 1 - 5;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_41) {
#line 300
  char *string = "(4+4*2)/1-5";
  double result1 = 0;
  double result2 = (4 + 4 * 2) / 1 - 5;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_42) {
#line 307
  char *string = "8*(6+7*4)+3";
  double result1 = 0;
  double result2 = 8 * (6 + 7 * 4) + 3;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_43) {
#line 315
  char *string = "2/(3+2)*5";
  double result1 = 0;
  double result2 = 2.0 / (3 + 2) * 5;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_44) {
#line 323
  char *string = "2+9.5-8^3/4+76.2";
  double result1 = 0;
  double result2 = 2 + 9.5 - pow(8, 3) / 4 + 76.2;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_45) {
#line 330
  char *string = "2+9.3-8^3/(4+56.2)";
  double result1 = 0;
  double result2 = (2 + 9.3 - pow(8, 3) / (4 + 56.2));
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_46) {
#line 338
  char *string = "(2^3)^2";
  double result1 = 0;
  double result2 = pow(pow(2, 3), 2);
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_47) {
#line 345
  char *string = "(2^3)^2";
  double result1 = 0;
  double result2 = pow(pow(2, 3), 2);
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_48) {
#line 352
  char *string = "3*sin(4+5)";
  double result1 = 0;
  double result2 = 3 * sin(4 + 5);
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_49) {
#line 359
  char *string = "431.2*2^2/8";
  double result1 = 0;
  double result2 = 431.2 * pow(2, 2) / 8;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_50) {
#line 366
  char *string = "cos(sin(2+9*6^1.2-tan(1)))";
  double result1 = 0;
  double result2 = cos(sin(2 + 9 * pow(6, 1.2) - tan(1)));
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_51) {
#line 373
  char *string = "sqrt(cos(sin(2+9*6^1.2-tan(1))))";
  double result1 = 0;
  double result2 = sqrt(cos(sin(2 + 9 * pow(6, 1.2) - tan(1))));
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_52) {
#line 380
  char *string = "sqrt(cos(sin(2+9*6^1.2-tan(1))))";
  double result1 = 0;
  double result2 = sqrt(cos(sin(2 + 9 * pow(6, 1.2) - tan(1))));
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_53) {
#line 387
  char *string = "sqrt(cos(sin(2+9*6^1.2-tan(1))))mod0.1";
  double result = 0;
  double x_number = 0;
  result = string_calc(string, x_number);
  ck_assert_double_eq_tol(result, 0.0615000, EPS);
}
END_TEST

START_TEST(test_54) {
#line 393
  char *string = "sqrt(2^2)*5/(4-3mod2)*(4-sqrt(81))";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, -16.6666667, EPS);
}
END_TEST

START_TEST(test_55) {
#line 399
  char *string = "cos(1/3)*sin(1.352^9/(4+3))";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.7876032, EPS);
}
END_TEST

START_TEST(test_56) {
#line 405
  char *string = "cos(6*3)/5";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.1320633, EPS);
}
END_TEST

START_TEST(test_57) {
#line 411
  char *string = "12.6.9+8";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_58) {
#line 418
  char *string = "(22+6";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_59) {
#line 424
  char *string = ")22+6(";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_60) {
#line 430
  char *string = "2++6";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_61) {
#line 436
  char *string = "()";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_62) {
#line 442
  char *string = "(*4-5)";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_63) {
#line 448
  char *string = "(.4-5)";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_64) {
#line 454
  char *string = "(,4-5)";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_65) {
#line 460
  char *string = "4-5/";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_66) {
#line 466
  char *string = "mod)";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_67) {
#line 472
  char *string = "mod5";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_68) {
#line 478
  char *string = "(mod5";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_69) {
#line 484
  char *string = "2.22.3";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_70) {
#line 490
  char *string = "/2.223-8";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_71) {
#line 496
  char *string = "55mod-";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_72) {
#line 502
  char *string = "*8+8";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_73) {
#line 508
  char *string = "8+8*";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_74) {
#line 514
  char *string = ")+1+(";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_75) {
#line 520
  char *string = "2.223-8/";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_76) {
#line 526
  char *string = ")";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_77) {
#line 532
  char *string = "(mod)";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_78) {
#line 538
  char *string = "8(8)";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_79) {
#line 544
  char *string = "(8)8";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_80) {
#line 550
  char *string = "d*";
  double result1 = 0;
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_81) {
#line 556
  char *string = "mod-2";
  double result1 = 0;
  result1 = validated(string);
  ck_assert_double_eq_tol(result1, 0.0000000, EPS);
}
END_TEST

START_TEST(test_82) {
#line 561
  char *string = "55mod4";
  double result1 = 0;
  result1 = validated(string);
  ck_assert_double_eq_tol(result1, 1, EPS);
}
END_TEST

START_TEST(test_83) {
#line 567
  char *string = "acos1";
  double result1 = 0;
  double result2 = acos(1);
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_84) {
#line 574
  char *string = "atan1";
  double result1 = 0;
  double result2 = atan(1);
  double x_number = 0;
  result1 = string_calc(string, x_number);
  ck_assert_double_eq_tol(result1, result2, EPS);
}
END_TEST

START_TEST(test_85) {
#line 582
  float credit_amount = 200000;
  int credit_term = 24;
  float credit_percentage_rate = 12;
  int repay_type = ANNUITY;
  float monthly_pay_first;
  float monthly_pay_last;
  float overpay;
  float total_repayment;
  credit_calc(credit_amount, credit_term, credit_percentage_rate, repay_type,
              &monthly_pay_first, &monthly_pay_last, &overpay,
              &total_repayment);
  ck_assert_double_eq_tol(monthly_pay_first, 9414.70, EPS2);
  ck_assert_double_eq_tol(monthly_pay_last, 9414.70, EPS2);
  ck_assert_double_eq_tol(round(overpay), 25953, EPS2);
  ck_assert_double_eq_tol(round(total_repayment), 225953.00, EPS2);
}
END_TEST

START_TEST(test_86) {
#line 597
  float credit_amount = 200000;
  int credit_term = 24;
  float credit_percentage_rate = 12;
  int repay_type = DIFFERENTIAL;
  float monthly_pay_first;
  float monthly_pay_last;
  float overpay;
  float total_repayment;
  credit_calc(credit_amount, credit_term, credit_percentage_rate, repay_type,
              &monthly_pay_first, &monthly_pay_last, &overpay,
              &total_repayment);
  ck_assert_double_eq_tol(monthly_pay_first, 10333.33, EPS2);
  ck_assert_double_eq_tol(monthly_pay_last, 8416.67, EPS2);
  ck_assert_double_eq_tol(round(overpay), 25000, EPS2);
  ck_assert_double_eq_tol(round(total_repayment), 225000.00, EPS2);
}
END_TEST

START_TEST(test_87) {
#line 613
  double Deposit_amount = 350000;
  int Deposit_term = 9;
  double Deposit_percent = 4.7;
  double Tax_rate = 13;
  int capitalize = CapQuarterly;
  double AccruedInterests;
  double TaxAmount;
  double DepositClosingAmount;
  deposit_calc(Deposit_amount, Deposit_term, Deposit_percent, Tax_rate,
               capitalize, &AccruedInterests, &TaxAmount,
               &DepositClosingAmount);
  ck_assert_double_eq_tol(AccruedInterests, 12483.03, EPS2);
  ck_assert_double_eq_tol(TaxAmount, 1622.79, EPS2);
  ck_assert_double_eq_tol(DepositClosingAmount, 362483.03, EPS2);
}
END_TEST

START_TEST(test_88) {
#line 627
  double Deposit_amount = 350000;
  int Deposit_term = 9;
  double Deposit_percent = 4.7;
  double Tax_rate = 13;
  int capitalize = CapHalfYear;
  double AccruedInterests;
  double TaxAmount;
  double DepositClosingAmount;
  deposit_calc(Deposit_amount, Deposit_term, Deposit_percent, Tax_rate,
               capitalize, &AccruedInterests, &TaxAmount,
               &DepositClosingAmount);
  ck_assert_double_eq_tol(AccruedInterests, 12409.70, EPS2);
  ck_assert_double_eq_tol(TaxAmount, 1613.26, EPS2);
  ck_assert_double_eq_tol(DepositClosingAmount, 362409.70, EPS2);
}
END_TEST

START_TEST(test_89) {
#line 642
  double Deposit_amount = 350000;
  int Deposit_term = 9;
  double Deposit_percent = 4.7;
  double Tax_rate = 13;
  double AccruedInterests;
  double TaxAmount;
  double DepositClosingAmount;
  deposit_calc_simple(Deposit_amount, Deposit_term, Deposit_percent, Tax_rate,
                      &AccruedInterests, &TaxAmount, &DepositClosingAmount);
  ck_assert_double_eq_tol(AccruedInterests, 12337.50, EPS2);
  ck_assert_double_eq_tol(TaxAmount, 1603.88, EPS2);
  ck_assert_double_eq_tol(DepositClosingAmount, 362337.50, EPS2);
}
END_TEST

START_TEST(test_90) {
#line 656
  double Deposit_amount = 350000;
  int Deposit_term = 12;
  double Deposit_percent = 4.7;
  double Tax_rate = 13;
  int capitalize = CapMonthly;
  double AccruedInterests;
  double TaxAmount;
  double DepositClosingAmount;
  deposit_calc(Deposit_amount, Deposit_term, Deposit_percent, Tax_rate,
               capitalize, &AccruedInterests, &TaxAmount,
               &DepositClosingAmount);
  ck_assert_double_eq_tol(AccruedInterests, 16809.03, EPS2);
  ck_assert_double_eq_tol(TaxAmount, 2185.17, EPS2);
  ck_assert_double_eq_tol(DepositClosingAmount, 366809.03, EPS2);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, test_0);
  tcase_add_test(tc1_1, test_1);
  tcase_add_test(tc1_1, test_2);
  tcase_add_test(tc1_1, test_3);
  tcase_add_test(tc1_1, test_4);
  tcase_add_test(tc1_1, test_5);
  tcase_add_test(tc1_1, test_6);
  tcase_add_test(tc1_1, test_7);
  tcase_add_test(tc1_1, test_8);
  tcase_add_test(tc1_1, test_9);
  tcase_add_test(tc1_1, test_10);
  tcase_add_test(tc1_1, test_11);
  tcase_add_test(tc1_1, test_12);
  tcase_add_test(tc1_1, test_13);
  tcase_add_test(tc1_1, test_14);
  tcase_add_test(tc1_1, test_15);
  tcase_add_test(tc1_1, test_16);
  tcase_add_test(tc1_1, test_17);
  tcase_add_test(tc1_1, test_18);
  tcase_add_test(tc1_1, test_19);
  tcase_add_test(tc1_1, test_20);
  tcase_add_test(tc1_1, test_21);
  tcase_add_test(tc1_1, test_22);
  tcase_add_test(tc1_1, test_22_a);
  tcase_add_test(tc1_1, test_23);
  tcase_add_test(tc1_1, test_24);
  tcase_add_test(tc1_1, test_25);
  tcase_add_test(tc1_1, test_26);
  tcase_add_test(tc1_1, test_27);
  tcase_add_test(tc1_1, test_28);
  tcase_add_test(tc1_1, test_29);
  tcase_add_test(tc1_1, test_30);
  tcase_add_test(tc1_1, test_31);
  tcase_add_test(tc1_1, test_32);
  tcase_add_test(tc1_1, test_33);
  tcase_add_test(tc1_1, test_34);
  tcase_add_test(tc1_1, test_35);
  tcase_add_test(tc1_1, test_36);
  tcase_add_test(tc1_1, test_37);
  tcase_add_test(tc1_1, test_38);
  tcase_add_test(tc1_1, test_39);
  tcase_add_test(tc1_1, test_40);
  tcase_add_test(tc1_1, test_41);
  tcase_add_test(tc1_1, test_42);
  tcase_add_test(tc1_1, test_43);
  tcase_add_test(tc1_1, test_44);
  tcase_add_test(tc1_1, test_45);
  tcase_add_test(tc1_1, test_46);
  tcase_add_test(tc1_1, test_47);
  tcase_add_test(tc1_1, test_48);
  tcase_add_test(tc1_1, test_49);
  tcase_add_test(tc1_1, test_50);
  tcase_add_test(tc1_1, test_51);
  tcase_add_test(tc1_1, test_52);
  tcase_add_test(tc1_1, test_53);
  tcase_add_test(tc1_1, test_54);
  tcase_add_test(tc1_1, test_55);
  tcase_add_test(tc1_1, test_56);
  tcase_add_test(tc1_1, test_57);
  tcase_add_test(tc1_1, test_58);
  tcase_add_test(tc1_1, test_59);
  tcase_add_test(tc1_1, test_60);
  tcase_add_test(tc1_1, test_61);
  tcase_add_test(tc1_1, test_62);
  tcase_add_test(tc1_1, test_63);
  tcase_add_test(tc1_1, test_64);
  tcase_add_test(tc1_1, test_65);
  tcase_add_test(tc1_1, test_66);
  tcase_add_test(tc1_1, test_67);
  tcase_add_test(tc1_1, test_68);
  tcase_add_test(tc1_1, test_69);
  tcase_add_test(tc1_1, test_70);
  tcase_add_test(tc1_1, test_71);
  tcase_add_test(tc1_1, test_72);
  tcase_add_test(tc1_1, test_73);
  tcase_add_test(tc1_1, test_74);
  tcase_add_test(tc1_1, test_75);
  tcase_add_test(tc1_1, test_76);
  tcase_add_test(tc1_1, test_77);
  tcase_add_test(tc1_1, test_78);
  tcase_add_test(tc1_1, test_79);
  tcase_add_test(tc1_1, test_80);
  tcase_add_test(tc1_1, test_81);
  tcase_add_test(tc1_1, test_82);
  tcase_add_test(tc1_1, test_83);
  tcase_add_test(tc1_1, test_84);
  tcase_add_test(tc1_1, test_85);
  tcase_add_test(tc1_1, test_86);
  tcase_add_test(tc1_1, test_87);
  tcase_add_test(tc1_1, test_88);
  tcase_add_test(tc1_1, test_89);
  tcase_add_test(tc1_1, test_90);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
